version: 1
policy:
  pullRequests: public
tasks:
  - $if: '(tasks_for == "github-pull-request"  && event["action"] in ["opened", "reopened", "synchronize"])'
    then:
      taskId: {$eval: as_slugid("test")}
      created: {$fromNow: ''}
      deadline: {$fromNow: '2 hours'}
      provisionerId: proj-taskcluster
      workerType: ci
      payload:
        maxRunTime: 3600
        image: golang:1.12.6
        command:
          - /bin/bash
          - '-c'
          - >-
            git clone ${event.pull_request.head.repo.git_url} taskcluster-worker-runner &&
            cd taskcluster-worker-runner &&
            git config advice.detachedHead false &&
            git checkout ${event.pull_request.head.sha} &&
            go test -v -race ./...
      metadata:
        name: taskcluster-worker-runner-tests
        description: runs tests for taskcluster-worker-runner components
        owner: taskcluster-internal@mozilla.com
        source: ${event.repository.url}

  - $if: '(tasks_for == "github-pull-request"  && event["action"] in ["opened", "reopened", "synchronize"])'
    then:
      taskId: {$eval: as_slugid("lint")}
      created: {$fromNow: ''}
      deadline: {$fromNow: '2 hours'}
      provisionerId: proj-taskcluster
      workerType: ci
      payload:
        maxRunTime: 3600
        image: golang:1.12.6
        command:
          - /bin/bash
          - '-c'
          - >-
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.17.1 &&
            git clone ${event.pull_request.head.repo.git_url} taskcluster-worker-runner &&
            cd taskcluster-worker-runner &&
            git config advice.detachedHead false &&
            git checkout ${event.pull_request.head.sha} &&
            golangci-lint run &&
            go run util/update-readme.go &&
            if ! output=$(git status --porcelain) || [ -n "$output" ]; then
              echo "*** 'go run util/update-readme.go' produced changes to the repository; these changes should be checked in ***";
              git --no-pager diff;
              exit 1;
            fi
      metadata:
        name: taskcluster-worker-runner-lint
        description: check lint for taskcluster-worker-runner
        owner: taskcluster-internal@mozilla.com
        source: ${event.repository.url}

  - $if: '(tasks_for == "github-pull-request"  && event["action"] in ["opened", "reopened", "synchronize"])'
    then:
      taskId: {$eval: as_slugid("winbuild")}
      created: {$fromNow: ''}
      deadline: {$fromNow: '2 hours'}
      provisionerId: proj-taskcluster
      workerType: ci
      payload:
        maxRunTime: 3600
        image: golang:1.12.6
        command:
          - /bin/bash
          - '-c'
          - >-
            git clone ${event.pull_request.head.repo.git_url} taskcluster-worker-runner &&
            cd taskcluster-worker-runner &&
            git config advice.detachedHead false &&
            git checkout ${event.pull_request.head.sha} &&
            GOOS=windows GOARCH=amd64 go build ./...
      metadata:
        name: taskcluster-worker-runner-windows-build
        description: perform a windows build of taskcluster-worker-runner
        owner: taskcluster-internal@mozilla.com
        source: ${event.repository.url}

  - $if: 'tasks_for == "github-push"'
    then:
      taskId: {$eval: as_slugid("all")}
      created: {$fromNow: ''}
      deadline: {$fromNow: '2 hours'}
      provisionerId: proj-taskcluster
      workerType: ci
      payload:
        maxRunTime: 3600
        image: golang:1.12.6
        command:
          - /bin/bash
          - '-c'
          - >-
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.17.1 &&
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh &&
            git clone ${event.repository.url} taskcluster-worker-runner &&
            cd taskcluster-worker-runner &&
            git config advice.detachedHead false &&
            git checkout ${event.after} &&
            golangci-lint run &&
            go test -v -race ./...
      metadata:
        name: taskcluster-worker-runner-everything
        description: all checks for taskcluster-worker-runner
        owner: taskcluster-internal@mozilla.com
        source: ${event.repository.url}
